#!/usr/bin/env bash
# https://github.com/srs/gradle-node-plugin/issues/24
set -Eeuo pipefail

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
GRADLEW="$DIR/../gradlew"
# This should match the "workDir" setting in build.gradle
PROJECTDIR="${DIR}/.."

NODE_HOME="$("$GRADLEW" -q -p "$PROJECTDIR" nodeDir | tail -n1)/bin"
PATH="${NODE_HOME}:${PATH}"
exec "${NODE_HOME}/npx" "$@"
